---
- name: Install java8
  apt:
     name: openjdk-8-jdk
     state: present
     update_cache: yes

- name: set java_home
  shell: echo JAVA_HOME is $JAVA_HOME
  environment:
    JAVA_HOME: "{{ java_home }}"
  register: shellout

- name: check java_home
  debug:
    var: shellout
