---
- name: Install apache2
  apt:
    name: apache2
    state: present
  notify: start apache2

- name: Enable ssl module
  apache2_module:
    name: ssl
    state: present
  notify: restart apache2

- name: Enable proxy_html module
  apache2_module:
     name: proxy_html
     state: present
  notify: restart apache2

- name: Enable proxy_http module
  apache2_module:
     name: proxy_http
     state: present
  notify: restart apache2

- name: Enable rewrite module
  apache2_module:
     name: rewrite
     state: present
  notify: restart apache2

- name: Enable request module
  apache2_module:
     name: request
     state: present
  notify: restart apache2

-  name: Enable headers module
   apache2_module:
     name: headers
     state: present
   notify: restart apache2
