- name: extract the tomcat binary
  unarchive:
    src: "{{ tomcat_url }}/{{ tomcat_archive}}"
    dest: "{{ tomcat_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    extra_opts: [--strip-components=1]
    mode: 0750
    remote_src: true
