---
tomcat_dir: "/opt/tomcat"
tomcat_user: "tomcat"
tomcat_group: "tomcat"
java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"

tomcat_version: "8.5.47"
tomcat_archive_format: "tar.gz"

installation_srclocation: "~/tarfile"
tomcat_archive: "apache-tomcat-{{ tomcat_version }}.{{ tomcat_archive_format }}"
tomcat_umask_value: 0007
